Update gatsby.yml

diff --git a/.github/workflows/gatsby.yml b/.github/workflows/gatsby.yml
--- a/.github/workflows/gatsby.yml
+++ b/.github/workflows/gatsby.yml
@@ -23,6 +23,22 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+        
+        
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
       
       - name: Setup Node Using Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v3
